### ISSUE TITLE
ext: do not use `pop` on entry point object

### ISSUE THREAD

**Issue by jirikuncar** [inveniosoftware/invenio-admin#32]
Problematic code:

- https://github.com/inveniosoftware/invenio-admin/blob/master/invenio_admin/ext.py#L76-L79

Proposal:

- create a copy of the global object first

**Comment by diegodelemos** [comment]
I think it is already being copied in the following line:
https://github.com/inveniosoftware/invenio-admin/blob/master/invenio_admin/ext.py#L70
