### ISSUE TITLE
template: AdminLTE template

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-admin#5]
Add AdminLTE template like in Invenio 2.x

https://almsaeedstudio.com/preview

**Comment by lnielsen** [comment]
or alternatively https://github.com/silverbux/bootflat-admin

**Comment by jirikuncar** [comment]
Moved to v1.0.0 as @eamonnmag would like to use it on http://hepdata.net

**Comment by lnielsen** [comment]
Just for the admin or for the entire site? and which one - bootflat-admin or adminlte? :-)

I think the best way to do it, would be creating a separate package with just these bootflat-admin templates. Then it would be useable by not only Invenio by all Flask-Admin instances and I don't think it would require much more effort.

Note, see also https://github.com/flask-admin/flask-admin/pull/1016#issuecomment-134437376

**Comment by lnielsen** [comment]
As well as previous work in https://github.com/inveniosoftware/invenio/pull/3263

**Comment by jirikuncar** [comment]
Closed via #31 and https://github.com/inveniosoftware/invenio-theme/pull/67
