### ISSUE TITLE
global: Talisman 0.5.1 incompatibility

### ISSUE THREAD

**Issue by slint** [inveniosoftware/invenio-admin#66]
The new patch version of Flask-Talisman removes the `local_options` member for the `Talisman` class, rendering [the CSP override "hack" ](https://github.com/inveniosoftware/invenio-admin/blob/72369022c40f05e59025b94b7896927b27d6f1d5/invenio_admin/views.py#L64-L78) ineffective. 

Since the patch is an "experimental" fix by the author of Flask-Talisman [to address some race condition issues](https://github.com/GoogleCloudPlatform/flask-talisman/issues/22). it might be better to pin to `<0.5.1` and wait to see if the issue is actually mitigated. In case it is, to upgrade to 0.5.1 we should attempt to override [the `flask_admin.base.BaseView._run_view` method](https://github.com/flask-admin/flask-admin/blob/7ea3f12e09d363dac836c5cde518dd6bcbb8173e/flask_admin/base.py#L356-L368) instead of `_handle_view` and set the `talisman_view_options` attribute appropriately.

**Comment by slint** [comment]
Seems like flask-talisman v0.6.0 has been out recently. Probably worth giving it a try to upgrade...

**Comment by ppanero** [comment]
@slint I have launched a new instance and tried with 0.6.0. However, when doing ``invenio index init`` I am getting:

```
/home/workspace/virtual_env/python34es6/bin/python /home/workspace/virtual_env/cernsearch/bin/invenio index init --force
Traceback (most recent call last):
  File "/home/workspace/virtual_env/cernsearch/bin/invenio", line 7, in <module>
    from invenio_app.cli import cli
  File "/home/workspace/virtual_env/python34es6/lib/python3.4/site-packages/invenio_app/__init__.py", line 160, in <module>
    from .ext import InvenioApp
  File "/home/workspace/virtual_env/python34es6/lib/python3.4/site-packages/invenio_app/ext.py", line 16, in <module>
    from flask_talisman import Talisman
  File "/home/workspace/virtual_env/python34es6/lib/python3.4/site-packages/flask_talisman/__init__.py", line 15, in <module>
    from .talisman import (
  File "/home/workspace/virtual_env/python34es6/lib/python3.4/site-packages/flask_talisman/talisman.py", line 360, in <module>
    get_random_string = secrets.token_urlsafe  # pragma: no cover
AttributeError: 'module' object has no attribute 'token_urlsafe'
```

**Comment by ppanero** [comment]
With ``invenio-app==1.1.0`` and ``flask-talisman==0.5.0`` I get 
```python
AttributeError: 'NoneType' object has no attribute 'local_options'
```
In 
```python
setattr(invenio_app.talisman.local_options,
```

What specific tests need to be carried out to check compatibility with ``flask-talisman==0.6.0``? Just the travis pipelines?

**Comment by lnielsen** [comment]
Please verify if there's anything needed for this issue still, or if it has been solved and can be closed.

**Comment by neilharrisbrown** [comment]
Plz fix https://github.com/inveniosoftware/invenio-app/issues/78
Its 3 years since it was fixed by talisman.
