### ISSUE TITLE
User Admin Permissions

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-admin#78]
This is a brain-dump / discussion thread about the following problem

**Problem**

(For us,) having access to the admin should not equate being able to do
everything in the admin. For instance we would like to differentiate between
librarians and super users: both should be able to access the admin, but
librarians should only see certain sections and should only be able to read
and edit records say (not delete them).

**Current situation**

Currently there doesn't seem to be a way to achieve this in Invenio. (This is where you chastise me for my misunderstanding of the current situation!)

Invenio-admin through its [ext.py](https://github.com/inveniosoftware/invenio-admin/blob/b5ff8f7de66d1d6b67efc9f81ff094eb2428f969/invenio_admin/ext.py#L41) protects admin
views visibility via the configurable [ADMIN_PERMISSION_FACTORY](https://github.com/inveniosoftware/invenio-admin/blob/b5ff8f7de66d1d6b67efc9f81ff094eb2428f969/invenio_admin/config.py#L28).
This only addresses the visibility problem (read permission of admin view if you will),
and not the action problem (create, update, delete associated with admin view).
Even then, it is placing the onus on the developer using invenio-admin to implement
a factory that would enforce visibility logic for all admin views of all modules
their instance happens to use.

**Community**

Maybe the logic is different per instances, but the structure to tie these
things together could be common. Supporting more complex permissions and different
roles [has been mentioned](https://github.com/inveniosoftware/invenio-access/issues/70#issuecomment-237165310) in the past in a similar context.

**A proposal**

I am less experienced than others with Invenio, so take the following as you will:

Invenio-admin provides a `ProtectedAdminView` (not just as a factory),
from which other invenio modules' `AdminView`s should inherit.

```python

class ProtectedAdminView(BaseView):
    """ProtectedAdminView"""
    def is_accessible(self):
        # Use configurable 'read' permission
        # else default functionality
        # (current_admin or start from config)
        pass

    def is_action_allowed(self, action):
        # Use configurable per action permission
        # else default functionality
        # (current_admin or start from config)
        if action == 'create':
            pass
        elif action == 'update':
            pass
        elif action == 'delete':
            pass
        if action == 'action':
            pass
```

The configuration for an instance could look like:

```python
ADMIN_PERMISSION_FACTORIES = {
    # <admin_view> to be replaced by the left hand value registered in the
    # `invenio_admin.views` entry point
    '<admin_viewA>': {
        'create': 'my_project.my_module.<admin_view>_create_permission',
        'read': 'my_project.my_module.<admin_view>_read_permission',
        'update': 'my_project.my_module.<admin_view>_update_permission',
        'delete': 'my_project.my_module.<admin_view>_delete_permission',
    },
    '<admin_viewB>': {
        # another set
        # any that are not defined just use the default
    }
}
```

This configuration could eventually replace `ADMIN_PERMISSION_FACTORY` itself.

To help provide a default functionality for each of these cases, it could be
standard for invenio-modules to create an ActionNeed() for each
`(<admin_view>, <action>)` pair.

There might be ways to automate the creation of this code structure, but because
the permissions should be fed to the `invenio_access.actions` entrypoint there might be
limits to what we can do here.

**Pros/Cons**

The benefit is that it solves the problem (right?).

The cons are:

- Requires a change in invenio-admin
- Requires a change in EVERY invenio-module that exposes an admin to use `ProtectedAdminView`
- Doesn't address custom actions on an admin view
  (could be extended for that, but let's keep it simple for now)
- Permissions can take some time to grok and that would add to it. Are we making permissions even messier?

**Alternatives**

The [enabling pattern](https://github.com/inveniosoftware/invenio-search/blob/cb4edcf7d56b60c26618e9da64e397653c326071/invenio_search/config.py#L65) can be
used to limit admin visibility in general, but it is:

- only for visibility and not actions
- non user-dependent
- requiring changes in all modules as well

I think [invenio-accounts](https://github.com/inveniosoftware/invenio-accounts) / [invenio-accounts-rest](https://github.com/inveniosoftware/invenio-accounts-rest) is trying to pull off something in that vicinity but I may be mistaken / don't understand it.

**Actions**

Feedback / discussion on this. Is this something a lot of others want and/or in scope for the invenioRDM? I am sure you must have thought about this and
come up with a better solution, but I wanted to have a place to get this issue discussed and get myself completely corrected ;)

@inveniosoftware/architects

**Comment by lnielsen** [comment]
Initially, I thought of the admin area as really only the area for admins, as some of the views exposed are basically just database table access. Librarians and other power-users would not access the admin area (``/admin/*``), but rather go through normal views tailored to their needs. 
Also, the admin interface is good for putting up some quick actions on the database, but it doesn't help expose REST APIs.

Example: User/role management would go through a Community Teams feature, rather than through the admin. The admin interface would display role names like ``community_blr_reader``, ``community_blr_writer``, ``community_blr_admin`` and would not be very user-friendly.

As said, that was the initial idea. I do see that there are good reasons to change this and allow more fine-grained permissions in the admin, but it probably requires a bit wider discussion.

**Comment by fenekku** [comment]
It is good that you mention the User/Role management, because it is something missing from invenio-access, right? 

Yes, in most cases, we can provide site pages/features that do the equivalent things. For instance, we do this already for librarian search and editing. I think the batch update feature might be served well by the admin. Maybe some of the database values in the admin can display the user-friendly values as well to help.

**Comment by jma** [comment]
Just to mention that we used custom admin view solve the same problem in RERO-ILS: limit access and visibility views depending of the role of the professional woking in a given library.

Basically we used `is_accessible` and `is_visible` class method:
https://github.com/rero/rero-ils/blob/master/rero_ils/modules/admin.py

We did this using `invenio_admin` to avoid to re-implement this kind of logic.

**Comment by fenekku** [comment]
Yes this is definitely the way to go for custom/own module views now. Reiterates the value in creating a setup so that someone *making* a custom view (module) and someone *using* it (instance) can easily setup their admin permissions.

**Comment by lnielsen** [comment]
Since I'm merging some things on the repo right now, I'm checking old issues as well :-)

For InvenioRDM (not Invenio Framework), we have disabled the admin. Also, the idea is to go with a custom admin interface that uses the REST API fully. The invenio-admin is not using our service layer and thus we risk have discrepancies what is allowed and not compared to the normal REST API. Also, the normal REST API provides fine grained control via the permission policies

I'm closing this issue as a won't fix for now.
