### ISSUE TITLE
[BLOCKED]global: fix deprecation warning

### ISSUE THREAD

**Issue by ChiaraBi** [inveniosoftware/invenio-admin#81]
`flask_admin/model/base.py:8: DeprecationWarning: The import 'werkzeug.secure_filename' is deprecated and will be removed in Werkzeug 1.0. Use 'from werkzeug.utils import secure_filename' instead.`

We have to wait until [this](https://github.com/flask-admin/flask-admin/blob/master/flask_admin/model/base.py#L8) will be fixed.

**Comment by equadon** [comment]
There is an open PR to fix this here: https://github.com/flask-admin/flask-admin/pull/1922
