### ISSUE TITLE
installation: bump invenio-accounts to fix build error

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-admin#87]
**Problem**
[Travis build error on lowest requirements](https://travis-ci.org/github/inveniosoftware/invenio-admin/jobs/680936202)

WTForms moving email validation to an optional dependency. This problem was fixed in invenio-accounts v1.1.4.

**Task:**
- Bump minimal version of invenio-accounts from v1.1.3 to v1.1.4 in ``setup.py``. This should fix the build error.

**Comment by ppanero** [comment]
For some reason, lowest is installing:
```
Collecting invenio-access>=1.0.0
470  Downloading invenio_access-1.4.0-py2.py3-none-any.whl (32 kB)
```

Which ends up requiring `invenio-accounts >=1.2.0`

Therefore I am not sure we can release backcompat to 1.1.3 (of invenio-admin).
